
font_family      Cousine Nerd Font
font_size 11
background_opacity 0.5
background_blur 32
cursor_trail 1
cursor_trail_decay 0.1 0.4
cursor_trail_start_threshold 2
# cursor_trail_color none

# Базовые комбинации без Shift
map ctrl+с send_key all c          # Ctrl+C (прерывание)
map ctrl+м send_key all v          # Ctrl+V (вставка из буфера, если используется)
map ctrl+ч send_key all x          # Ctrl+X (вырезать)

# Дополнительно: Ctrl+Z (приостановка) - русская 'я' на клавише 'z'
map ctrl+я send_key all z



