[mgr]

prepend_keymap = [
  { on = ["g", "o"], run = "plugin duckdb -open", desc = "open with duckdb" },
  {on   = "e", run  = "plugin toggle-pane min-preview", desc = "Show or hide the preview pane"},
  {on   = "E", run  = "plugin toggle-pane max-preview", desc = "Maximize or restore the preview pane"},
  {on="R",run  = "plugin recycle-bin -- menu",desc = "Open the trash menu" },
  { on = [ "T" ], run = "shell kitty", desc = "Открыть терминал в текущей папке" },
  { on = [ "g", "G" ], run = "shell --block lazygit", desc = "Запустить lazygit" },
  { on = [ "c", "z" ], run = "shell '7z a -tzip \"${1%.*}.zip\" \"$@\"'", desc = "Создать ZIP-архив" },
  { on = [ "c", "7" ], run = "shell '7z a \"${1%.*}.7z\" \"$@\"'", desc = "Создать 7z-архив" },
  { on = [ "c", "p" ], run = "shell --block '7z a -tzip -p \"${1%.*}.zip\" \"$@\"'", desc = "Создать ZIP с паролем" },

  # Mount devices
  {on  = "M", run = "plugin mount"},

  # GVFS
    { on = [ "V", "m" ], run = "plugin gvfs -- select-then-mount --jump", desc = "Select device to mount and jump to its mount point" },
    { on = [ "V", "R" ], run = "plugin gvfs -- remount-current-cwd-device", desc = "Remount device under cwd" },
    { on = [ "V", "u" ], run = "plugin gvfs -- select-then-unmount ", desc = "Select device then unmount" },
    # Add Scheme/Mount URI:
    { on = [ "V", "a" ], run = "plugin gvfs -- add-mount", desc = "Add a GVFS mount URI" },
    # Edit a Scheme/Mount URI
    { on = [ "V", "e" ], run = "plugin gvfs -- edit-mount", desc = "Edit a GVFS mount URI" },
    # Remove a Scheme/Mount URI
    { on = [ "V", "r" ], run = "plugin gvfs -- remove-mount", desc = "Remove a GVFS mount URI" },

    # Jump
    { on = [ "g", "m" ], run = "plugin gvfs -- jump-to-device --automount", desc = "Automount then select device to jump to its mount point" },
    { on = [ "`", "`" ], run = "plugin gvfs -- jump-back-prev-cwd", desc = "Jump back to the position before jumped to device" },
]


